version: "3.9"
services:
  loan-service:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    networks:
      - vksviit-network
    depends_on:
      - loan-db
  loan-db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loans
      MYSQL_USER: loan_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3706:3306"
    networks:
      - vksviit-network
networks:
  vksviit-network: null
